# Generated by Django 6.0.5 on 2026-08-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajePatrocinio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa o Marca')),
                ('contacto', models.CharField(max_length=200, verbose_name='Persona de Contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('interes', models.CharField(choices=[('naming', 'Main Sponsor (Naming Rights)'), ('apparel', 'Indumentaria y Equipamiento'), ('digital', 'Digital & Streaming Partner'), ('other', 'Activaciones y BTL en recinto')], max_length=20, verbose_name='Nivel de Interés')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje Adicional')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
            ],
            options={
                'verbose_name': 'Mensaje de Patrocinio',
                'verbose_name_plural': 'Mensajes de Patrocinio',
                'ordering': ['-creado'],
            },
        ),
    ]
