"""
Django settings for LMVEweb project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from csp.constants import NONCE, NONE, SELF
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# En producción las variables las provee el hosting directamente; acá solo
# hace falta para que el .env local (no versionado) se cargue en desarrollo.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Seguro por defecto: si se olvida definir la variable en el hosting, la
# app arranca en modo producción (sin páginas de error con el stack trace
# completo) en vez de quedar en modo debug por accidente.
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# En desarrollo (DEBUG=True) alcanza con no definir DJANGO_SECRET_KEY: se
# usa esta clave de siempre (ya expuesta en el historial del repo, nunca
# usar fuera de un entorno local). En producción es obligatoria: si falta,
# la app no arranca, en vez de exponer secretos con una clave conocida.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-)muka9a326k(l*$yofxwa&r+_(8q*#a**$$ifryf6t3tm=#bz8'
    else:
        raise ImproperlyConfigured(
            'Falta la variable de entorno DJANGO_SECRET_KEY '
            '(obligatoria cuando DJANGO_DEBUG no es True).'
        )

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]

# Enlace temporal para mostrarle el avance a alguien más (reenvío de
# puertos de VS Code, ngrok o Cloudflare Tunnel). Se activa a propósito
# con DJANGO_SHARE_TUNNEL=True y no afecta a producción.
if os.environ.get('DJANGO_SHARE_TUNNEL', 'False') == 'True':
    DOMINIOS_TUNEL = [
        '.devtunnels.ms',
        '.ngrok-free.app',
        '.ngrok.io',
        '.trycloudflare.com',
    ]
    ALLOWED_HOSTS += DOMINIOS_TUNEL
    # Necesario para que el formulario de Contacto siga funcionando
    # cuando se accede por https a través del túnel.
    CSRF_TRUSTED_ORIGINS = ['https://*' + d for d in DOMINIOS_TUNEL]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_ratelimit',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LMVEweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LMVEweb.wsgi.application'


# Correo saliente (formulario de Contacto)
# https://docs.djangoproject.com/en/6.0/topics/email/
#
# Gmail con contraseña de aplicación: en myaccount.google.com/apppasswords
# (requiere verificación en dos pasos activada) se genera una clave de 16
# caracteres para usar acá en vez de la contraseña real de la cuenta.
#
# Sin EMAIL_HOST_USER/EMAIL_HOST_PASSWORD (desarrollo local), los correos
# no se envían de verdad: solo se imprimen en la terminal.
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or 'webmaster@localhost'

# A qué correo llega cada envío del formulario de Contacto. Por defecto,
# el mismo que envía (útil si todavía no hay una casilla dedicada).
CONTACTO_DESTINATARIO = os.environ.get('CONTACTO_DESTINATARIO', EMAIL_HOST_USER)


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Si el hosting entrega la variable de entorno DATABASE_URL (ej. Postgres
# administrado), se usa esa. Si no existe (desarrollo local), se sigue
# usando el mismo db.sqlite3 de siempre.
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Carpeta donde `collectstatic` junta todos los estáticos para producción.
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        # Whitenoise: permite que el propio Django sirva CSS/JS/imágenes en
        # producción de forma eficiente, sin necesitar un servidor aparte.
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# Seguridad para HTTPS (producción)
# https://docs.djangoproject.com/en/6.0/topics/security/
#
# Envuelto en "if not DEBUG" para no forzar HTTPS en desarrollo local
# (runserver sirve por http:// sin certificado).
# Cache en base de datos: la usa el rate limiting del formulario de
# Contacto (django-ratelimit). Tiene que ser compartida entre los workers
# de Gunicorn en producción, por eso no alcanza con la caché en memoria
# por defecto (cada worker tendría su propio conteo). La tabla la crea
# "python manage.py createcachetable" (ver Procfile, release phase).
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_table',
    }
}

# django-ratelimit solo da por "soportados" sin advertencia a Memcached o
# Redis, porque son los únicos con incremento atómico garantizado. Sumar
# cualquiera de los dos es un servicio de infraestructura nuevo que este
# proyecto no necesita todavía: para el volumen de un formulario de
# auspicios de una liga escolar, una condición de carrera ocasional (que
# deje pasar 1-2 intentos de más bajo tráfico concurrente real) no es un
# riesgo que justifique esa complejidad. Se acepta la advertencia y se
# silencia solo el error puntual de "no atómico" (E003), no todo el check.
SILENCED_SYSTEM_CHECKS = ['django_ratelimit.E003']

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Content-Security-Policy (django-csp)
# https://django-csp.readthedocs.io/
#
# Estricta: sin 'unsafe-inline'. Cada <style>/<script> inline de las
# plantillas lleva nonce="{{ request.csp_nonce }}" (django-csp genera uno
# distinto por request). Dominios externos permitidos explícitamente:
# - cdnjs.cloudflare.com: three.js (proyecto.html/sobre.html)
# - www.instagram.com: embed.js + el iframe que inyecta para los posts
#   embebidos en home.html (script-src para el script, frame-src para el
#   iframe, connect-src porque el widget pide datos del post por XHR)
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': [SELF],
        'script-src': [SELF, NONCE, 'cdnjs.cloudflare.com', 'www.instagram.com'],
        'style-src': [SELF, NONCE],
        'img-src': [SELF, 'data:'],
        'connect-src': [SELF, 'www.instagram.com'],
        'frame-src': ['www.instagram.com'],
        'base-uri': [SELF],
        'frame-ancestors': [NONE],
    },
}


# Logging
# https://docs.djangoproject.com/en/6.0/topics/logging/
#
# Handler de consola siempre activo: con DEBUG=False los errores ya no se
# muestran en pantalla, así que esto es lo mínimo para que no queden
# completamente invisibles (por ejemplo, en los logs de Render) aunque
# todavía no haya Sentry configurado.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'core': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Sentry (opcional): sin SENTRY_DSN en el entorno, simplemente no se activa.
SENTRY_DSN = os.environ.get('SENTRY_DSN')
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=0.1,
        send_default_pii=False,
    )
